#!/usr/bin/env bash
# ============================================================
#  Papital ERP — Updater
#  Backs up the database, pulls the latest source, rebuilds,
#  restarts the service and verifies health.
#  Migrations run automatically at startup (NEVER db:push).
#
#  Usage:
#    ./update.sh                     # git-based update (default)
#    ./update.sh --no-backup         # git-based update, skip backup (discouraged)
#    ./update.sh --source <DIR>      # manual update from an extracted source directory
#    ./update.sh --zip <FILE.zip>    # manual update from a source zip archive
# ============================================================
set -euo pipefail

LOG_FILE="update-$(date +%Y%m%d-%H%M%S).log"
exec > >(tee -a "$LOG_FILE") 2>&1

APP_DIR="${APP_DIR:-/opt/papital-erp}"
SERVICE_NAME="papital-erp"
APP_PORT="${APP_PORT:-3000}"
SKIP_BACKUP=0
SOURCE_DIR=""
SOURCE_ZIP=""

# ---------- Parse arguments ----------
while [ $# -gt 0 ]; do
  case "$1" in
    --no-backup) SKIP_BACKUP=1 ;;
    --source)    shift; SOURCE_DIR="${1:-}"; [ -n "$SOURCE_DIR" ] || die "--source requires a directory path"; ;;
    --zip)       shift; SOURCE_ZIP="${1:-}"; [ -n "$SOURCE_ZIP" ] || die "--zip requires an archive path"; ;;
    *)           die "Unknown argument: $1 (supported: --no-backup, --source <DIR>, --zip <FILE.zip>)" ;;
  esac
  shift
done

log()      { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
success()  { log "OK: $*"; }
warn()     { log "WARN: $*"; }
die()      { log "ERROR: $*"; exit 1; }

log "=== Papital ERP Updater — log file: $LOG_FILE ==="
cd "$APP_DIR" || die "Application directory not found: $APP_DIR"
[ -f .env ] || die ".env not found in $APP_DIR"

# ---------- Manual mode: extract zip / locate source directory ----------
if [ -n "$SOURCE_ZIP" ]; then
  [ -f "$SOURCE_ZIP" ] || die "Zip archive not found: $SOURCE_ZIP"
  STAGE_DIR="$(mktemp -d /tmp/papital-src.XXXXXX)"
  log "Extracting source archive $SOURCE_ZIP -> $STAGE_DIR ..."
  unzip -q -o "$SOURCE_ZIP" -d "$STAGE_DIR" || die "Failed to extract archive."
  # Support archives that wrap everything in a single top-level folder
  ENTRIES="$(find "$STAGE_DIR" -mindepth 1 -maxdepth 1 | wc -l)"
  if [ "$ENTRIES" -eq 1 ] && [ -d "$(find "$STAGE_DIR" -mindepth 1 -maxdepth 1 -type d)" ]; then
    STAGE_DIR="$(find "$STAGE_DIR" -mindepth 1 -maxdepth 1 -type d)"
  fi
  [ -f "$STAGE_DIR/package.json" ] && [ -f "$STAGE_DIR/server.ts" ] \
    || die "Extracted archive does not look like a Papital ERP source tree (missing package.json/server.ts)."
  SOURCE_DIR="$STAGE_DIR"
fi

if [ -n "$SOURCE_DIR" ]; then
  [ -d "$SOURCE_DIR" ] || die "Source directory not found: $SOURCE_DIR"
  [ -f "$SOURCE_DIR/package.json" ] && [ -f "$SOURCE_DIR/server.ts" ] \
    || die "Source directory does not look like an application source tree (missing package.json/server.ts)."
  UPDATE_MODE="manual"
  log "Update mode: MANUAL (source directory: $SOURCE_DIR)"
else
  UPDATE_MODE="git"
  log "Update mode: GIT (git pull --ff-only)"
fi

if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1; then
  SUDO="sudo"
else
  SUDO=""
fi

# ---------- 1) Pre-update database backup ----------
if [ "$SKIP_BACKUP" -eq 0 ]; then
  log "[1/6] Creating pre-deployment database backup..."
  # scripts/backup.sh reads DATABASE_URL from .env and tags the dump as pre-deployment
  if [ -f scripts/backup.sh ]; then
    set -a; . ./.env; set +a
    BACKUP_KIND=pre-deployment bash scripts/backup.sh || die "Database backup failed — aborting update."
  else
    warn "scripts/backup.sh not found — skipping explicit backup step."
  fi
else
  warn "Backup skipped by --no-backup flag."
fi

# ---------- 2) Update source ----------
if [ "$UPDATE_MODE" = "git" ]; then
  # AI Studio pulls delete package-lock.json; a stale local copy would block --ff-only.
  # Remove it pre-pull — step [3/6] regenerates it (and node_modules) deterministically.
  if [ -f package-lock.json ] && ! git ls-files --error-unmatch package-lock.json >/dev/null 2>&1; then
    warn "Stale untracked package-lock.json found (regenerated by a previous run) — removing before pull."
    rm -f package-lock.json
  fi
  log "[2/6] Pulling latest source (git pull --ff-only)..."
  git pull --ff-only || die "git pull failed (local changes or divergence). Resolve manually, then re-run."
else
  log "[2/6] Syncing source from $SOURCE_DIR (state-preserving rsync)..."
  command -v rsync >/dev/null 2>&1 || die "rsync is required for manual updates (apt-get install -y rsync)."
  # Preserve live state: .env, git history, logs, uploads, backups, db data, node_modules, dist, installer logs
  rsync -a \
    --exclude='.env' \
    --exclude='.git/' \
    --exclude='logs/' \
    --exclude='install-*.log' \
    --exclude='update-*.log' \
    --exclude='domain-setup-*.log' \
    --exclude='.pgdata/' \
    --exclude='backups/' \
    --exclude='public/uploads/' \
    --exclude='node_modules/' \
    --exclude='dist/' \
    --exclude='*.zip' \
    "$SOURCE_DIR"/ "$APP_DIR"/ || die "Source sync failed. Live installation is untouched — investigate and retry."
  if [ -n "$SOURCE_ZIP" ]; then
    rm -rf "${STAGE_DIR:-}" && success "Temporary extraction directory removed."
  fi
  success "Source synced."
fi

# ---------- 3) Install & build ----------
# NOTE: .env (sourced above for the backup) exports NODE_ENV=production which makes
# npm omit devDependencies — but the build (vite/esbuild) REQUIRES them (v4.0.30 split).
# Force full install for the build step only; runtime keeps NODE_ENV=production.
log "[3/6] Installing dependencies (npm ci --include=dev)..."
# AI Studio pulls delete package-lock.json; npm ci cannot run without it.
if [ ! -f package-lock.json ]; then
  warn "package-lock.json missing — regenerating from package.json (npm install --package-lock-only)..."
  NODE_ENV=development npm install --include=dev --package-lock-only --no-audit --no-fund \
    || die "Lockfile regeneration failed."
fi
NODE_ENV=development npm ci --include=dev || {
  warn "npm ci failed — lockfile is likely out of sync with package.json. Regenerating and retrying..."
  NODE_ENV=development npm install --include=dev --package-lock-only --no-audit --no-fund \
    || die "Lockfile regeneration failed."
  NODE_ENV=development npm ci --include=dev || die "npm ci failed even after lockfile regeneration."
}
log "[4/6] Building application..."
npm run build
success "Build completed."

# ---------- 4) Restart service ----------
PKG_VERSION="$(node -p "require('./package.json').version" 2>/dev/null || echo '')"
RESTART_OK=0
# NOTE: string matching instead of `systemctl | grep -q` — under `set -o pipefail`,
# grep -q exits early and SIGPIPEs systemctl, making the pipeline falsely fail.
UNIT_LIST="$(systemctl list-unit-files 2>/dev/null || true)"
log "[5/6] Restarting service..."
if [[ "$UNIT_LIST" != *"$SERVICE_NAME.service"* ]]; then
  # Auto-detect the systemd unit managing the running app (unit may have a custom name)
  RUNNING_PID="$(pgrep -f 'dist/server.cjs' | head -1 || true)"
  if [ -n "$RUNNING_PID" ]; then
    DETECTED="$(systemctl status "$RUNNING_PID" 2>/dev/null | grep -oE '[a-zA-Z0-9_.@-]+\.service' | head -1 | sed 's/\.service$//' || true)"
    if [ -n "$DETECTED" ] && [ "$DETECTED" != "systemd" ]; then
      warn "No unit named '${SERVICE_NAME}' found — auto-detected managing unit: '${DETECTED}'"
      SERVICE_NAME="$DETECTED"
    fi
  fi
fi
if [[ "$UNIT_LIST" == *"$SERVICE_NAME.service"* ]]; then
  $SUDO systemctl restart "$SERVICE_NAME" && RESTART_OK=1
elif command -v pm2 >/dev/null 2>&1 && pm2 id "$SERVICE_NAME" >/dev/null 2>&1; then
  pm2 restart "$SERVICE_NAME" && RESTART_OK=1
else
  warn "No systemd unit or pm2 process named '${SERVICE_NAME}' found — start the app manually."
fi

# ---------- 5) Health verification ----------
log "[6/6] Verifying health..."
HEALTH_OK=0
for i in $(seq 1 30); do
  if curl -fsS "http://localhost:${APP_PORT}/health/live" >/dev/null 2>&1; then
    HEALTH_OK=1
    break
  fi
  sleep 2
done
[ "$HEALTH_OK" -eq 1 ] || die "Health probe failed after restart. Check: journalctl -u ${SERVICE_NAME} -n 100"

# ---------- 5b) Version consistency: the RUNNING process must serve the NEW build ----------
HEALTH_VERSION="$(curl -fsS "http://localhost:${APP_PORT}/health" | grep -oE '"version":"[^"]+"' | head -1 | cut -d'"' -f4 || true)"
if [ -n "$PKG_VERSION" ] && [ "$HEALTH_VERSION" != "$PKG_VERSION" ]; then
  die "Runtime version (v${HEALTH_VERSION:-unknown}) does NOT match the freshly built package.json (v$PKG_VERSION).
The service was NOT restarted with the new build (old process still running).
Fix: stop the old process and start the app properly (systemd unit 'papital-erp' recommended — see install.sh), then re-verify:
  curl -fsS http://localhost:${APP_PORT}/health | grep version"
fi
if [ "$RESTART_OK" -ne 1 ]; then
  die "Health probe passed BUT no managed service was restarted — the running process may still be an old build. Register a systemd/pm2 service and re-run."
fi
success "Update finished successfully. Runtime v$HEALTH_VERSION == build v$PKG_VERSION"

log "NOTE: Schema migrations run automatically at startup. NEVER run 'npm run db:push'."
exit 0
