import 'dotenv/config';
import { orm } from '../src/db/drizzle.js';
import { sql } from 'drizzle-orm';
import { DataReconciliationService } from '../src/services/reconciliation/dataReconciliation.service.js';

/**
 * TD-036 Scoped Test Data Cleanup & Sequence Recalibration Script
 * =================================================================
 * Identifies and removes all synthetic test artifacts generated by prior
 * in-app test runs, E2E suites, concurrency benchmarks, and penetration tests.
 * Safely preserves authentic configuration, chart of accounts, master data,
 * real users, and production business records.
 */

async function main() {
  const isDryRun = process.argv.includes('--dry-run');

  console.log('=====================================================');
  console.log('🧹 TD-036: Scoped Test Data Cleanup & Recalibration');
  console.log(`Mode: ${isDryRun ? '🔍 DRY RUN (Preview only)' : '⚡ LIVE PURGE (--force)'}`);
  console.log('=====================================================\n');

  // Define synthetic patterns
  const TEST_DOC_COND = sql`(
    ref_number ILIKE 'CP-FIN-%' OR ref_number ILIKE 'DOC\\_%' OR ref_number ILIKE 'DOC-%'
    OR ref_number ILIKE 'STRESS-%' OR ref_number ILIKE 'IDEM-%' OR ref_number ILIKE 'ROLLBACK-%'
    OR ref_number ILIKE 'DOC_RACE%' OR ref_number ILIKE 'PURCHASE-E2E-%' OR ref_number ILIKE 'INV-E2E-%'
    OR ref_number ILIKE 'WOO-ORDER-%' OR ref_number ILIKE 'E2E-%' OR ref_number ILIKE 'TEST-%'
    OR ref_number ILIKE 'V9-%' OR ref_number ILIKE 'V9\\_%' OR ref_number ILIKE 'DIAG-%'
    OR notes ILIKE '%آزمایشی%' OR notes ILIKE '%E2E%' OR notes ILIKE '%تست%'
    OR buyer_name ILIKE '%آزمایشی%' OR buyer_name ILIKE '%استرس%' OR buyer_name ILIKE '%مسابقه نهاییسازی%'
    OR buyer_name ILIKE '%مشتری سازمانی تست%'
  )`;

  const TEST_ITEM_COND = sql`(
    code ILIKE 'ITEM\\_%' OR code ILIKE 'STRESS-%' OR code ILIKE 'SILVER-%' OR code ILIKE 'NECKLACE-%'
    OR code ILIKE 'WOO-%' OR code ILIKE 'DIAG\\_%' OR code ILIKE 'V9\\_%' OR code ILIKE 'V9-%'
    OR code ILIKE '1405-N-101-%' OR code ILIKE 'V10-CANARY-%'
    OR name ILIKE '%آزمایشی%' OR name ILIKE '%استرس%' OR name ILIKE '%فاز ۱۴%' OR name ILIKE '%فاز 14%'
    OR name ILIKE '%تستی%'
  )`;

  const TEST_VOUCHER_COND = sql`(
    description ILIKE '%آزمایشی%' OR description ILIKE '%E2E%' OR description ILIKE '%تست%'
    OR description ILIKE '%مسابقه نهاییسازی%' OR description ILIKE '%آزمون تغییرناپذیری%'
    OR description ILIKE '%سند ابطال و برگشت جهت بازثبت%' OR description ILIKE '%سند بازثبت‌شده (Repost)%'
    OR description ILIKE '%سند اولیه جهت تست برگشت%' OR description ILIKE '%سند آزمایشی متوازن%'
    OR reference_number ILIKE 'WOO-ORDER-%' OR reference_number ILIKE 'PURCHASE-E2E-%'
    OR reference_number ILIKE 'INV-E2E-%' OR reference_number ILIKE 'PAY-%' OR reference_number ILIKE 'V9-%'
    OR reference_number ILIKE 'CP-FIN-%' OR reference_number ILIKE 'VOID-REPOST-%'
    OR reference_number ILIKE 'REPOST-%' OR reference_number ILIKE 'REV-V%' OR reference_number ILIKE 'TEST-%'
    OR (reference_module = 'invoice' AND reference_id IN (SELECT id FROM documents WHERE ${TEST_DOC_COND}))
    OR (reference_module = 'payroll' AND reference_id IN (SELECT id FROM piecework_payrolls WHERE payroll_number ILIKE 'PAY-%' OR title ILIKE '%آزمایشی%'))
  )`;

  const TEST_CUSTOMER_COND = sql`(
    name ILIKE '%آزمایشی%' OR name ILIKE '%طرف حساب آزمایشی%' OR name ILIKE 'مشتری سازمانی تست%'
    OR name ILIKE '%تست برگشت حسابداری%' OR notes ILIKE '%آزمایشی%'
  )`;

  const TEST_PERSONNEL_COND = sql`(
    full_name ILIKE '%آزمایشی%' OR full_name ILIKE '%فاز ۱۴%' OR full_name ILIKE '%فاز 14%'
    OR full_name ILIKE '%پرسنل تستی%' OR full_name ILIKE '%پرسنل تستی کارمزدی%'
  )`;

  const TEST_USER_COND = sql`(
    username ILIKE 'testuser_%' OR username ILIKE 'test_%' OR username ILIKE 'e2e_%'
    OR username ILIKE 'user_%' OR username ILIKE 'pen_admin%' OR username ILIKE 'sec009_%'
    OR username ILIKE 'v9_%' OR full_name ILIKE '%کاربر آزمایشی%'
  )`;

  const TEST_CRM_LEAD_COND = sql`(
    title ILIKE '%آزمایشی%' OR title ILIKE '%تست%' OR company ILIKE '%آزمایشی%'
    OR customer_name ILIKE '%آزمایشی%' OR customer_name ILIKE '%مشتری سازمانی تست%'
  )`;

  // 1. Audit counts
  const countQuery = async (query: any) => {
    const res: any = await orm.execute(query);
    return Number(res.rows?.[0]?.c ?? 0);
  };

  const audit = {
    testVoucherItems: await countQuery(sql`SELECT count(*)::int as c FROM journal_voucher_items WHERE voucher_id IN (SELECT id FROM journal_vouchers WHERE ${TEST_VOUCHER_COND})`),
    testVouchers: await countQuery(sql`SELECT count(*)::int as c FROM journal_vouchers WHERE ${TEST_VOUCHER_COND}`),
    testDocItems: await countQuery(sql`SELECT count(*)::int as c FROM document_items WHERE document_id IN (SELECT id FROM documents WHERE ${TEST_DOC_COND})`),
    testTransactions: await countQuery(sql`SELECT count(*)::int as c FROM transactions WHERE document_id IN (SELECT id FROM documents WHERE ${TEST_DOC_COND}) OR item_id IN (SELECT id FROM items WHERE ${TEST_ITEM_COND}) OR document_ref ILIKE 'V9-%' OR document_ref ILIKE 'DIAG-%' OR document_ref ILIKE 'REVERSAL-%'`),
    testTreasury: await countQuery(sql`SELECT count(*)::int as c FROM treasury_transactions WHERE document_id IN (SELECT id FROM documents WHERE ${TEST_DOC_COND}) OR party_name ILIKE '%آزمایشی%' OR party_name ILIKE '%استرس%'`),
    testDocuments: await countQuery(sql`SELECT count(*)::int as c FROM documents WHERE ${TEST_DOC_COND}`),
    testItemPrices: await countQuery(sql`SELECT count(*)::int as c FROM item_prices WHERE item_id IN (SELECT id FROM items WHERE ${TEST_ITEM_COND})`),
    testItems: await countQuery(sql`SELECT count(*)::int as c FROM items WHERE ${TEST_ITEM_COND}`),
    testCustomers: await countQuery(sql`SELECT count(*)::int as c FROM customers WHERE ${TEST_CUSTOMER_COND}`),
    testPersonnel: await countQuery(sql`SELECT count(*)::int as c FROM personnel WHERE ${TEST_PERSONNEL_COND}`),
    testPieceworkLogs: await countQuery(sql`SELECT count(*)::int as c FROM piecework_logs WHERE notes ILIKE '%آزمایشی%' OR notes ILIKE '%تست%' OR personnel_id IN (SELECT id FROM personnel WHERE ${TEST_PERSONNEL_COND})`),
    testPayrolls: await countQuery(sql`SELECT count(*)::int as c FROM piecework_payrolls WHERE payroll_number ILIKE 'PAY-%' OR title ILIKE '%آزمایشی%' OR title ILIKE '%تست%'`),
    testDailyLogs: await countQuery(sql`SELECT count(*)::int as c FROM daily_work_logs WHERE title ILIKE '%آزمایشی%' OR title ILIKE '%تست%' OR content ILIKE '%آزمایشی%'`),
    testCrmActivities: await countQuery(sql`SELECT count(*)::int as c FROM crm_activities WHERE title ILIKE '%آزمایشی%' OR title ILIKE '%تست%'`),
    testCrmLeads: await countQuery(sql`SELECT count(*)::int as c FROM crm_leads WHERE ${TEST_CRM_LEAD_COND}`),
    testUsers: await countQuery(sql`SELECT count(*)::int as c FROM users WHERE ${TEST_USER_COND}`),
    testWorkflowInstances: await countQuery(sql`SELECT count(*)::int as c FROM workflow_instances`),
    testOutbox: await countQuery(sql`SELECT count(*)::int as c FROM outbox_events`),
    testDeadLetter: await countQuery(sql`SELECT count(*)::int as c FROM dead_letter_events`),
    testIdempotency: await countQuery(sql`SELECT count(*)::int as c FROM idempotency_keys`),
  };

  console.log('📊 Identified Test Artifacts Breakdown:');
  console.table(audit);

  const totalArtifacts = Object.values(audit).reduce((acc, curr) => acc + curr, 0);
  console.log(`\nTotal test artifacts identified: ${totalArtifacts}`);

  if (isDryRun) {
    console.log('\n🔍 DRY RUN Complete. No records were modified or deleted.');
    process.exit(0);
  }

  if (totalArtifacts === 0) {
    console.log('\n✨ Database is already clean. No test artifacts found.');
  } else {
    console.log('\n🚀 Starting transaction-safe cleanup execution...');

    await orm.transaction(async (tx) => {
      // 1. Workflow runtime
      await tx.execute(sql`DELETE FROM workflow_history_logs`);
      await tx.execute(sql`DELETE FROM workflow_tasks`);
      await tx.execute(sql`DELETE FROM workflow_pending_approvals`);
      await tx.execute(sql`DELETE FROM workflow_instances`);
      await tx.execute(sql`DELETE FROM workflow_delegations`);
      await tx.execute(sql`DELETE FROM workflow_transitions WHERE workflow_definition_id IN (SELECT id FROM workflow_definitions WHERE code ILIKE 'WF_%' OR title ILIKE '%آزمایشی%')`);
      await tx.execute(sql`DELETE FROM workflow_states WHERE workflow_definition_id IN (SELECT id FROM workflow_definitions WHERE code ILIKE 'WF_%' OR title ILIKE '%آزمایشی%')`);
      await tx.execute(sql`DELETE FROM workflow_definitions WHERE code ILIKE 'WF_%' OR title ILIKE '%آزمایشی%'`);

      // 2. Piecework & Payroll
      await tx.execute(sql`DELETE FROM piecework_logs WHERE notes ILIKE '%آزمایشی%' OR notes ILIKE '%تست%' OR personnel_id IN (SELECT id FROM personnel WHERE ${TEST_PERSONNEL_COND}) OR payroll_id IN (SELECT id FROM piecework_payrolls WHERE payroll_number ILIKE 'PAY-%' OR title ILIKE '%آزمایشی%')`);
      await tx.execute(sql`DELETE FROM piecework_payrolls WHERE payroll_number ILIKE 'PAY-%' OR title ILIKE '%آزمایشی%' OR title ILIKE '%تست%'`);
      await tx.execute(sql`DELETE FROM personnel WHERE ${TEST_PERSONNEL_COND}`);

      // 3. Projects & Daily logs
      await tx.execute(sql`DELETE FROM daily_work_logs WHERE title ILIKE '%آزمایشی%' OR title ILIKE '%تست%' OR content ILIKE '%آزمایشی%' OR user_id IN (SELECT id FROM users WHERE ${TEST_USER_COND})`);
      await tx.execute(sql`DELETE FROM project_bom_allocations WHERE item_id IN (SELECT id FROM items WHERE ${TEST_ITEM_COND}) OR project_id IN (SELECT id FROM production_projects WHERE project_code ILIKE 'PROJ_%' OR project_code ILIKE 'E2E_%' OR title ILIKE '%آزمایشی%')`);
      await tx.execute(sql`DELETE FROM project_stages WHERE project_id IN (SELECT id FROM production_projects WHERE project_code ILIKE 'PROJ_%' OR project_code ILIKE 'E2E_%' OR title ILIKE '%آزمایشی%')`);
      await tx.execute(sql`DELETE FROM production_projects WHERE project_code ILIKE 'PROJ_%' OR project_code ILIKE 'E2E_%' OR title ILIKE '%آزمایشی%'`);

      // 4. CRM & Proforma references
      await tx.execute(sql`UPDATE crm_leads SET proforma_id = NULL WHERE proforma_id IN (SELECT id FROM documents WHERE ${TEST_DOC_COND})`);
      await tx.execute(sql`DELETE FROM crm_activities WHERE title ILIKE '%آزمایشی%' OR title ILIKE '%تست%' OR lead_id IN (SELECT id FROM crm_leads WHERE ${TEST_CRM_LEAD_COND})`);
      await tx.execute(sql`DELETE FROM crm_leads WHERE ${TEST_CRM_LEAD_COND}`);

      // 5. Treasury & Cheques references to vouchers/documents
      await tx.execute(sql`UPDATE cheques SET voucher_id = NULL WHERE voucher_id IN (SELECT id FROM journal_vouchers WHERE ${TEST_VOUCHER_COND})`);
      await tx.execute(sql`DELETE FROM cheques WHERE drawer_name ILIKE '%آزمایشی%' OR payee_name ILIKE '%آزمایشی%' OR description ILIKE '%آزمایشی%'`);
      await tx.execute(sql`DELETE FROM treasury_transactions WHERE document_id IN (SELECT id FROM documents WHERE ${TEST_DOC_COND}) OR party_name ILIKE '%آزمایشی%' OR party_name ILIKE '%استرس%' OR voucher_id IN (SELECT id FROM journal_vouchers WHERE ${TEST_VOUCHER_COND})`);

      // 6. Accounting Vouchers
      await tx.execute(sql`DELETE FROM journal_voucher_items WHERE voucher_id IN (SELECT id FROM journal_vouchers WHERE ${TEST_VOUCHER_COND})`);
      await tx.execute(sql`DELETE FROM journal_vouchers WHERE ${TEST_VOUCHER_COND}`);

      // 7. Documents, Transactions, Stock
      await tx.execute(sql`DELETE FROM document_items WHERE document_id IN (SELECT id FROM documents WHERE ${TEST_DOC_COND}) OR item_id IN (SELECT id FROM items WHERE ${TEST_ITEM_COND})`);
      await tx.execute(sql`DELETE FROM transactions WHERE document_id IN (SELECT id FROM documents WHERE ${TEST_DOC_COND}) OR item_id IN (SELECT id FROM items WHERE ${TEST_ITEM_COND}) OR document_ref ILIKE 'V9-%' OR document_ref ILIKE 'DIAG-%' OR document_ref ILIKE 'REVERSAL-%'`);
      await tx.execute(sql`DELETE FROM documents WHERE ${TEST_DOC_COND}`);

      // 8. Items
      await tx.execute(sql`DELETE FROM item_prices WHERE item_id IN (SELECT id FROM items WHERE ${TEST_ITEM_COND})`);
      await tx.execute(sql`DELETE FROM items WHERE ${TEST_ITEM_COND}`);

      // 9. Customers
      await tx.execute(sql`DELETE FROM customers WHERE ${TEST_CUSTOMER_COND}`);

      // 10. System events, idempotency keys & queues (delete before users to satisfy FK)
      await tx.execute(sql`DELETE FROM idempotency_keys`);
      await tx.execute(sql`DELETE FROM outbox_events`);
      await tx.execute(sql`DELETE FROM dead_letter_events`);
      await tx.execute(sql`DELETE FROM event_action_logs`);

      // 11. Users (test only)
      await tx.execute(sql`DELETE FROM form_drafts WHERE user_id IN (SELECT id FROM users WHERE ${TEST_USER_COND})`);
      await tx.execute(sql`DELETE FROM notifications WHERE user_id IN (SELECT id FROM users WHERE ${TEST_USER_COND}) OR sender_id IN (SELECT id FROM users WHERE ${TEST_USER_COND})`);
      await tx.execute(sql`DELETE FROM activity_logs WHERE user_id IN (SELECT id FROM users WHERE ${TEST_USER_COND}) OR action ILIKE 'TEST%' OR details::text ILIKE '%E2E%' OR details::text ILIKE '%آزمایشی%'`);
      await tx.execute(sql`DELETE FROM users WHERE ${TEST_USER_COND}`);

      console.log('✅ Purge completed inside transaction.');
    });
  }

  // 11. Sequence & Counter Recalibration
  console.log('\n🔢 Recalibrating PostgreSQL Sequences & Document Counters...');
  try {
    // Journal Voucher sequence
    const maxVoucherRes: any = await orm.execute(sql`SELECT COALESCE(MAX(voucher_number), 0)::int as max_v FROM journal_vouchers`);
    const maxVoucher = Number(maxVoucherRes.rows?.[0]?.max_v ?? 0);
    const nextVoucher = Math.max(1, maxVoucher + 1);
    await orm.execute(sql`SELECT setval('journal_voucher_number_seq', ${nextVoucher}, false)`);
    console.log(`  - journal_voucher_number_seq reset to next value: ${nextVoucher} (Current max in DB: ${maxVoucher})`);

    // Treasury Transaction sequence
    const maxTreasuryRes: any = await orm.execute(sql`
      SELECT COALESCE(MAX(SUBSTRING(transaction_number FROM '[0-9]+')::int), 0) as max_t 
      FROM treasury_transactions
    `);
    const maxTreasury = Number(maxTreasuryRes.rows?.[0]?.max_t ?? 0);
    const nextTreasury = Math.max(1, maxTreasury + 1);
    await orm.execute(sql`SELECT setval('treasury_tx_number_seq', ${nextTreasury}, false)`);
    console.log(`  - treasury_tx_number_seq reset to next value: ${nextTreasury} (Current max in DB: ${maxTreasury})`);

    // Document Ref Counters
    await orm.execute(sql`
      INSERT INTO document_ref_counters (doc_type, fiscal_year, last_ref_number)
      VALUES 
        ('invoice', 1405, (SELECT COALESCE(MAX(SUBSTRING(ref_number FROM '^[0-9]+')::int), 0) FROM documents WHERE type = 'invoice')),
        ('purchase', 1405, (SELECT COALESCE(MAX(SUBSTRING(ref_number FROM '^[0-9]+')::int), 0) FROM documents WHERE type = 'purchase')),
        ('proforma', 1405, (SELECT COALESCE(MAX(SUBSTRING(ref_number FROM '^[0-9]+')::int), 0) FROM documents WHERE type = 'proforma')),
        ('waste', 1405, (SELECT COALESCE(MAX(SUBSTRING(ref_number FROM '^[0-9]+')::int), 0) FROM documents WHERE type = 'waste')),
        ('production_receipt', 1405, (SELECT COALESCE(MAX(SUBSTRING(ref_number FROM '^[0-9]+')::int), 0) FROM documents WHERE type = 'production_receipt')),
        ('production_issue', 1405, (SELECT COALESCE(MAX(SUBSTRING(ref_number FROM '^[0-9]+')::int), 0) FROM documents WHERE type = 'production_issue'))
      ON CONFLICT (doc_type, fiscal_year) DO UPDATE
      SET last_ref_number = EXCLUDED.last_ref_number
    `);
    console.log('  - document_ref_counters calibrated to real documents.');

    // Item Code Counters
    await orm.execute(sql`DELETE FROM item_code_counters`);
    console.log('  - item_code_counters initialized cleanly.');
  } catch (err: any) {
    console.error('⚠️ Sequence recalibration error:', err.message);
  }

  // 12. Run Data Integrity Reconciliation Scan
  console.log('\n🔎 Running 12-Point Data Integrity Reconciliation Scan...');
  try {
    const scan = await DataReconciliationService.scanIntegrity();
    console.log(`Integrity scan result: ${scan.healthy ? '✅ 100% HEALTHY' : '⚠️ ANOMALIES DETECTED'}`);
    console.log(`Checked metrics: ${scan.totalChecks}, Anomalies: ${scan.anomaliesCount}, Critical: ${scan.criticalCount}`);
    if (scan.anomalies.length > 0) {
      for (const anom of scan.anomalies) {
        console.log(`  - [${anom.severity.toUpperCase()}] ${anom.category} (${anom.entity}): ${anom.description}`);
      }
    } else {
      console.log('  - No integrity anomalies detected across all 12 validation domains.');
    }
  } catch (err: any) {
    console.error('Integrity scan error:', err.message);
  }

  console.log('\n🎉 Cleanup & Recalibration Completed Successfully!');
  process.exit(0);
}

main().catch((err) => {
  console.error('Fatal error during cleanup:', err);
  process.exit(1);
});
